apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microstral.config" . }}
data:
  POSTGRES_HOST: {{ include "postgres.fullname" . }}
  POSTGRES_PORT: {{ .Values.postgres.service.port }}
  POSTGRES_DB: "{{ .Values.postgres.database.name }}"
  POSTGRES_USER: "{{ .Values.postgres.database.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.database.password }}"
  REDIS_HOST: {{ include "redis.fullname" . }}
  REDIS_PORT: {{ .Values.redis.service.port }}
  REDIS_PASSWORD: "{{ .Values.redis.password }}"