apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.pvcname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.postgresql.persistence.size }}"
